stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - build-as-docker
  script:
    - docker build -t registry.njuics.cn/$CI_PROJECT_PATH:${CI_COMMIT_SHA:0:8} .
    - docker push registry.njuics.cn/$CI_PROJECT_PATH:${CI_COMMIT_SHA:0:8}

deploy:
  stage: deploy
  tags:
    - build-as-docker
  script:
    - deploy $CI_PROJECT_PATH ${CI_COMMIT_SHA:0:8}

